import React from 'react'
import type { Metadata } from 'next'

export const metadata: Metadata = {
    title: 'About | Next JS',
    description: 'Generated by create next app',
}

const AboutPage = () => {
  return (
    <div className='h-screen flex items-center justify-center'>
      <div className="lg:container max-w-7xl px-4 sm:px-6 md:px-10 lg:px-14 xl:px-24 mx-auto">
        <h1 className="text-5xl font-bold">
          About page
        </h1>
      </div>
    </div>
  )
}

export default AboutPage